// Get_COURSES
export const GET_COURSES_REQUEST = 'GET_COURSES_REQUEST';
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const GET_COURSES_FAILED = 'GET_COURSES_FAILED';


// Get_SUBJECTS
export const GET_SUBJECTS_REQUEST = 'GET_SUBJECTS_REQUEST';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const GET_SUBJECTS_FAILED = 'GET_SUBJECTS_FAILED';

// Get_LESSONS
export const GET_LESSONS_REQUEST = 'GET_LESSONS_REQUEST';
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS';
export const GET_LESSONS_FAILED = 'GET_LESSONS_FAILED';

// SET_LESSON_PROGRESS
export const SET_LESSON_PROGRESS = 'SET_LESSON_PROGRESS';
